"""LLM-powered Report Builder — generates structured relationship analysis reports."""
import json
from app.services.llm_provider_service import LLMProviderService


REPORT_SYSTEM_PROMPT = """You are a professional relationship analyst generating a detailed report for a client.

Based on the provided relationship data, generate a comprehensive JSON report with these sections:
{
  "summary": "2-3 sentence executive summary",
  "relationship_overview": {
    "stage": "current relationship stage",
    "status": "current status",
    "goal": "stated or inferred goal",
    "duration_context": "known timeline context"
  },
  "bazi_analysis": {
    "user_day_master": "user's day master and element",
    "partner_day_master": "partner's day master and element if known",
    "element_compatibility": "five elements compatibility assessment",
    "zodiac_compatibility": "zodiac compatibility summary",
    "key_insights": ["3-5 bazi-specific insights"]
  },
  "psychology_analysis": {
    "attachment_dynamic": "attachment style assessment",
    "communication_patterns": "identified patterns",
    "strengths": ["2-3 relationship strengths"],
    "growth_areas": ["2-3 growth areas"],
    "recommendations": ["2-3 actionable recommendations"]
  },
  "key_events": ["summary of 3-5 most significant relationship events"],
  "future_outlook": "1-2 paragraph forward-looking assessment with appropriate caveats",
  "action_plan": ["3-5 concrete next steps prioritized"]
}

Rules:
- Keep each string value under 200 characters.
- Be concise: bullet points, not paragraphs.
- Be honest and direct. Do not sugarcoat problems.
- Always include appropriate caveats: no absolute guarantees.
- If data is missing for a section, note it and provide what you can.
- Keep each section concise but substantive.
"""


class ReportBuilderService:
    def __init__(self) -> None:
        self.llm = LLMProviderService()

    def build_report(self, context: dict) -> dict:
        prompt = self._build_context_prompt(context)

        try:
            raw = self.llm.generate_text(REPORT_SYSTEM_PROMPT, prompt)
            return self._parse_json(raw)
        except Exception:
            return self._fallback_report(context)

    def build_markdown(self, report_json: dict) -> str:
        lines = []
        lines.append(f"# Relationship Analysis Report\n")

        if "summary" in report_json:
            lines.append(f"## Summary\n{report_json['summary']}\n")

        if "relationship_overview" in report_json:
            ro = report_json["relationship_overview"]
            lines.append("## Relationship Overview")
            for k, v in ro.items():
                lines.append(f"- **{k.replace('_', ' ').title()}**: {v}")
            lines.append("")

        if "bazi_analysis" in report_json:
            ba = report_json["bazi_analysis"]
            lines.append("## Bazi (Chinese Astrology) Analysis")
            for k, v in ba.items():
                if isinstance(v, list):
                    lines.append(f"**{k.replace('_', ' ').title()}**:")
                    for item in v:
                        lines.append(f"  - {item}")
                else:
                    lines.append(f"- **{k.replace('_', ' ').title()}**: {v}")
            lines.append("")

        if "psychology_analysis" in report_json:
            pa = report_json["psychology_analysis"]
            lines.append("## Psychology Analysis")
            for k, v in pa.items():
                if isinstance(v, list):
                    lines.append(f"**{k.replace('_', ' ').title()}**:")
                    for item in v:
                        lines.append(f"  - {item}")
                else:
                    lines.append(f"- **{k.replace('_', ' ').title()}**: {v}")
            lines.append("")

        if report_json.get("key_events"):
            lines.append("## Key Relationship Events")
            for e in report_json["key_events"]:
                lines.append(f"- {e}")
            lines.append("")

        if "future_outlook" in report_json:
            lines.append(f"## Future Outlook\n{report_json['future_outlook']}\n")

        if report_json.get("action_plan"):
            lines.append("## Action Plan")
            for i, a in enumerate(report_json["action_plan"], 1):
                lines.append(f"{i}. {a}")
            lines.append("")

        lines.append("---\n*Generated by AI Relationship Oracle. This report provides analysis and suggestions, not definitive predictions.*")
        return "\n".join(lines)

    def _build_context_prompt(self, context: dict) -> str:
        parts = ["Generate a relationship analysis report based on the following data:\n"]

        if context.get("user_profile"):
            p = context["user_profile"]
            parts.append(f"User: gender={p.get('gender')}, birth_date={p.get('birth_date')}, zodiac={p.get('bazi_chart', {}).get('zodiac') if p.get('bazi_chart') else 'unknown'}")

        if context.get("partner"):
            p = context["partner"]
            parts.append(f"Partner: nickname={p.get('nickname')}, zodiac={p.get('bazi_chart', {}).get('zodiac') if p.get('bazi_chart') else 'unknown'}")

        if context.get("relationship_profile"):
            rp = context["relationship_profile"]
            parts.append(f"Relationship: status={rp.current_status}, goal={rp.current_goal}, stage={rp.relationship_stage}, trust={rp.trust_level}, conflict={rp.conflict_level}")

        if context.get("events"):
            parts.append(f"Recent events ({len(context['events'])}):")
            for e in context["events"][:10]:
                parts.append(f"  - [{e.event_type}] {e.description[:200]}")

        if context.get("summary"):
            parts.append(f"Memory summary: {context['summary'].summary}")

        return "\n".join(parts)

    @staticmethod
    def _parse_json(raw: str) -> dict:
        raw = raw.strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[-1]
            if raw.endswith("```"):
                raw = raw.rsplit(chr(96)*3,1)[0]
        try:
            return json.loads(raw.strip())
        except json.JSONDecodeError:
            return ReportBuilderService._fallback_report({})

    @staticmethod
    def _fallback_report(context: dict) -> dict:
        return {
            "summary": "Report generation encountered an issue. Please try again.",
            "relationship_overview": {"stage": "unknown", "status": "unknown", "goal": "unknown"},
            "bazi_analysis": {"key_insights": ["Insufficient data for Bazi analysis"]},
            "psychology_analysis": {"recommendations": ["Consider discussing your relationship with a professional"]},
            "key_events": [],
            "future_outlook": "Unable to generate outlook at this time.",
            "action_plan": ["Try generating the report again with more relationship context"],
        }
