"""LLM-powered Report Builder ? returns Markdown directly, no JSON parsing needed."""
from app.services.llm_provider_service import LLMProviderService
from app.services.prompt_center_service import get_prompt_center


REPORT_MD_PROMPT = """You are a professional relationship analyst. Generate a comprehensive relationship analysis report in Markdown format directly. Do NOT output JSON.

The report MUST include these sections as Markdown headers:

# Relationship Analysis Report

## Summary
(2-3 sentence executive summary)

## Relationship Overview
- Stage, status, goal, key dynamic

## Bazi (Chinese Astrology) Analysis
- Day masters, five elements, zodiac compatibility
- Key insights and compatibility assessment

## Psychology Analysis
- Attachment styles, communication patterns
- Strengths and growth areas

## Tarot Guidance
- Card drawn and its meaning in this relationship context
- Symbolic insights

## Key Insights
- Cross-dimensional synthesis
- Main risks and opportunities

## Action Plan
1. First actionable step
2. Second actionable step
3. Third actionable step

---
*Generated by AI Relationship Oracle.*

Rules:
- Be warm, supportive, and non-judgmental.
- Use the provided Bazi/psychology/tarot data naturally.
- Never make absolute predictions. Use "may", "tends to", "suggests".
- Keep the report under 800 words.
"""


class ReportBuilderService:
    def __init__(self) -> None:
        self.prompt_center = get_prompt_center()
        self.llm = LLMProviderService()

    def build_report(self, context: dict) -> tuple[str, dict]:
        prompt = self._build_context_prompt(context)
        try:
            system_prompt = REPORT_MD_PROMPT
            raw = self.llm.generate_text(system_prompt, prompt)
            return raw, {"status": "ok"}
        except Exception:
            return self._fallback_report()

    def build_markdown(self, report_text: str) -> str:
        return report_text

    def _build_context_prompt(self, context: dict) -> str:
        parts = ["Generate a relationship analysis report in Markdown based on:\n"]

        up = context.get("user_profile")
        if up:
            bazi = up.get("bazi_chart") or {}
            elems = up.get("five_elements") or {}
            parts.append(f"User: gender={up.get('gender')}, birth={up.get('birth_date')}")
            if bazi:
                parts.append(f"  Day Master: {bazi.get('day_master', '?')}({bazi.get('day_master_element', '?')})")
                parts.append(f"  Zodiac: {bazi.get('zodiac', '?')}")
            if elems:
                parts.append(f"  Five Elements: {elems.get('counts', {})}, Dominant: {elems.get('dominant', '?')}")
            pillars = bazi.get("pillars", [])
            if pillars:
                parts.append(f"  Pillars: {' | '.join(p['pillar']+':'+p['stem']+p['branch'] for p in pillars)}")

        p = context.get("partner")
        if p:
            pb = p.get("bazi_chart") or {}
            parts.append(f"Partner: nickname={p.get('nickname')}, birth={p.get('birth_date')}")
            if pb:
                parts.append(f"  Day Master: {pb.get('day_master', '?')}({pb.get('day_master_element', '?')})")
                parts.append(f"  Zodiac: {pb.get('zodiac', '?')}")
            pbp = pb.get("pillars", [])
            if pbp:
                parts.append(f"  Pillars: {' | '.join(pp['pillar']+':'+pp['stem']+pp['branch'] for pp in pbp)}")

        rp = context.get("relationship_profile")
        if rp:
            parts.append(f"Relationship: status={rp.current_status}, goal={rp.current_goal}, stage={rp.relationship_stage}, trust={rp.trust_level}, conflict={rp.conflict_level}")

        ev = context.get("events")
        if ev:
            parts.append(f"Recent events ({len(ev)}):")
            for e in ev[:10]:
                parts.append(f"  - [{e.event_type}] {e.description[:200]}")

        s = context.get("summary")
        if s:
            parts.append(f"Memory: {s.summary}")

        return "\n".join(parts)

    @staticmethod
    def _fallback_report() -> tuple[str, dict]:
        md = """# Relationship Analysis Report
## Summary
Report generation encountered an issue. Please try again with more relationship context.

## Action Plan
1. Have a conversation with your partner
2. Try generating the report again later

---
*Generated by AI Relationship Oracle.*
"""
        return md, {"status": "fallback"}
