"""create relationship_event and relationship_event_candidate tables

Revision ID: 656fb9cecac6
Revises: 20260604_0004
Create Date: 2026-06-04 14:22:16.373067
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '656fb9cecac6'
down_revision: Union[str, None] = '20260604_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_event_partner_id'), 'relationship_event', ['partner_id'], unique=False)
    op.create_index(op.f('ix_relationship_event_user_id'), 'relationship_event', ['user_id'], unique=False)
    op.create_table('relationship_event_candidate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('candidate_status', sa.String(length=32), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_event_candidate_partner_id'), 'relationship_event_candidate', ['partner_id'], unique=False)
    op.create_index(op.f('ix_relationship_event_candidate_user_id'), 'relationship_event_candidate', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_event_candidate_user_id'), table_name='relationship_event_candidate')
    op.drop_index(op.f('ix_relationship_event_candidate_partner_id'), table_name='relationship_event_candidate')
    op.drop_table('relationship_event_candidate')
    op.drop_index(op.f('ix_relationship_event_user_id'), table_name='relationship_event')
    op.drop_index(op.f('ix_relationship_event_partner_id'), table_name='relationship_event')
    op.drop_table('relationship_event')
    # ### end Alembic commands ###
